name: 'Gettext Auto-update'
description: 'Push the new gettext template and translations when required'
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  translation_branch:
    description: 'The name of a branch that contains translation files'
    required: false
  regenerate_po:
    description: 'Also regenerate the .po files'
    required: false
  appstream_file:
    description: 'The path to the AppStream XML file to be updated with translation completion percentages if specified'
    required: false
  native_language:
    description: 'The native language to be specified as 100% complete in the AppStream file if specified'
    required: false
    default: 'en'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'message-circle'
  color: 'green'
