name: 'Release'
description: 'Generate changelogs and publish new versions'
inputs:
  dryrun:
    description: 'dry run option'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
branding:
  icon: 'git-pull-request'
  color: 'green'
